name: 'ASLBanPluginsAddon'
author: 'Andre_601'
version: '${plugin.version}'

main: 'ch.andre601.advancedserverlist.banplugins.paper.PaperBanPluginsAddon'

api-version: '1.19'

dependencies: 
  server: 
    AdvancedServerList:
      required: false
      load: BEFORE
    AdvancedBan:
      required: false
      load: BEFORE
    LibertyBans:
      required: false
      load: BEFORE
    LiteBans:
      required: false
      load: BEFORE