when:
  - event: tag
    branch: master

steps:
  - name: 'BuildJarAndUpload'
    image: maven:3.9.6-eclipse-temurin-17
    secrets:
      - modrinth_api_token
      - hangar_api_token
      - discord_webhook_url
    environment:
      CODEBERG_API_TOKEN:
        from_secret: cb_token
    commands:
      # Create the jar files.
      - mvn clean install
      # Move VersionUploader jar file
      - cd version-uploader/target/
      - mv VersionUploader.jar ../../
      - cd ../../
      # Execute Jar file
      - java -jar VersionUploader.jar --all
  - name: 'UploadJarsToCodeberg'
    image: woodpeckerci/plugin-gitea-release
    settings:
      base_url: https://codeberg.org
      files:
        - "bungeecord/target/AdvancedServerList-*.jar"
        - "paper/target/AdvancedServerList-*.jar"
        - "velocity/target/AdvancedServerList-*.jar"
        - "addons/banplugins/target/AdvancedServerList-*.jar"
      api_key:
        from_secret: cb_token
  - name: 'CreatePostOnMastodon'
    image: woodpeckerci/plugin-mastodon-post
    when:
      - status: ['success']
    settings:
      server_url: https://blobfox.coffee
      access_token:
        from_secret: mastodon_token
      status: |-
        ${CI_COMMIT_TAG} of #AdvancedServerList has been released and can be found on #Modrinth, #Hangar and #Codeberg!
        
        Modrinth https://modrinth.com/plugin/advancedserverlist
        Hangar https://hangar.papermc.io/Andre_601/AdvancedServerList
        Codeberg https://codeberg.org/Andre601/AdvancedServerList
      visibility: public