when:
  - event: tag
    branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: "Build Jar and Upload"
    image: maven:3.9.9-eclipse-temurin-21
    environment:
      CODEBERG_API_TOKEN:
        from_secret: cb_token
      MODRINTH_API_TOKEN:
        from_secret: modrinth_api_token
      HANGAR_API_TOKEN:
        from_secret: hangar_api_token
      DISCORD_WEBHOOK_URL:
        from_secret: discord_webhook_url
    commands:
      - mvn clean install
      - cd version-uploader/target
      - mv VersionUploader.jar ../../
      - cd ../../
      - java -jar VersionUploader.jar --all
  - name: "Upload Jars to Codeberg"
    image: woodpeckerci/plugin-gitea-release
    settings:
      base_url: https://codeberg.org
      files:
        - "bungeecord/target/AdvancedServerList-*.jar"
        - "paper/target/AdvancedServerList-*.jar"
        - "velocity/target/AdvancedServerList-*.jar"
        - "addons/banplugins/target/AdvancedServerList-*.jar"
      api_key:
        from_secret: cb_token
  - name: "Create Post on Mastodon"
    image: woodpeckerci/plugin-mastodon-post
    when:
      - status: ["success"]
    settings:
      server_url: https://swiss.social
      access_token:
        from_secret: mastodon_token
      status: |-
        #AdvancedServerList was updated to ${CI_COMMIT_TAG} and can be downloaded from #Modrinth, #Hangar and #Codeberg!
        
        Modrinth - https://modrinth.com/plugin/advancedserverlist
        Hangar - https://hangar.papermc.io/Andre_601/AdvancedServerList
        Codeberg - https://codeberg.org/Andre601/AdvancedServerList
      visibility: public
  - name: "Create Post on Bluesky"
    image: woodpeckerci/plugin-bluesky-post
    when:
      - status: ["success"]
    settings:
      identifier: andre601.ch
      app_password:
        from_secret: bluesky_app_password
      languages: english
      text: |-
        #AdvancedServerList was updated to ${CI_COMMIT_TAG} and can be downloaded from #Modrinth, #Hangar and #Codeberg!

        Modrinth -  https://modrinth.com/plugin/advancedserverlist
        Hangar - https://hangar.papermc.io/Andre_601/AdvancedServerList
        Codeberg - https://codeberg.org/Andre601/AdvancedServerList