blank_issues_enabled: false
contact_links:
  - name: API Support
    about: For API support, please create an issue in the `asl-api` repository.
    url: https://codeberg.org/Andre601/asl-api
  - name: Discord Server
    about: Please ask questions in the `#asl-support` channel on the M.O.S.S. Discord Server.
    url: https://discord.gg/MyPTjpsgGH
  - name: Wiki
    about: Check the Wiki for explanations about the features and examples.
    url: https://asl.andre601.ch