name: 'AdvancedServerList'
author: 'Andre_601'
version: '${plugin.version}'
description: '${plugin.description}'

main: 'ch.andre601.advancedserverlist.paper.PaperCore'

api-version: '1.20.6'

folia-supported: true

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    ViaVersion:
      load: BEFORE
      required: false
    Maintenance:
      load: BEFORE
      required: false
    ServerListPlus:
      load: BEFORE
      required: false